### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by nobet78** [hacker-cb/hassio-component-smart-thermostat#12]
Hello

I can't figure out how to configure, please help. 
My config:

  - platform: smart_thermostat    
    name: Gabinet PWM
    unique_id: gabinet_pwm
    target_sensor: sensor.gabinet_temperature
    min_temp: 18
    max_temp: 25
    precision: 0.5    
    heater:
      - entity_id: switch.6_rt_24v_piec
      - entity_id: switch.4_petla_gabinet
        inverted: true
        pid_params: 0.1, 0.001, 0
        pid_sample_period: "00:01:00"
        pwm_period: "00:05:00"

i am getting such error:

Logger: homeassistant
Source: custom_components/smart_thermostat/controllers.py:707
Integration: smart_thermostat ([documentation](https://github.com/jethome-ru/hassio-component-smart-thermostat))
First occurred: 20:15:43 (51 occurrences)
Last logged: 20:18:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/smart_thermostat/controllers.py", line 707, in _async_pwm_control
    if not self.__running:
AttributeError: 'PwmSwitchPidController' object has no attribute '_PwmSwitchPidController__running'

**Comment by hacker-cb** [comment]
My floor thermostats:

```yaml

    - platform: smart_thermostat
      name: floor_thermostat_kitchen
      heater:
        entity_id:  switch.wb1_wb_mr6c_28_k2
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
        # hot_tolerance: 0
        # cold_tolerance: 0
      target_sensor: sensor.floor_temperature_kitchen
      min_temp: 18
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: floor_thermostat_livingroom_middle
      heater:
        entity_id:  switch.wb1_wb_mr6c_28_k3
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
        # hot_tolerance: 0
        # cold_tolerance: 0
      target_sensor: sensor.floor_temperature_livingroom_middle
      min_temp: 18
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: floor_thermostat_livingroom_east
      heater:
        entity_id: switch.wb1_wb_mr6c_28_k4
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
        # hot_tolerance: 0
        # cold_tolerance: 0
      target_sensor: sensor.floor_temperature_livingroom_east
      min_temp: 18
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: floor_thermostat_room_1_floor
      heater:
        entity_id:  switch.wb1_wb_mr6c_28_k5
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
        # hot_tolerance: 0
        # cold_tolerance: 0
      target_sensor: sensor.floor_temperature_room_1_floor
      min_temp: 18
      max_temp: 34
      precision: 0.1

    - platform: smart_thermostat
      name: floor_thermostat_entrance
      heater:
        entity_id:  switch.wb1_wb_mr6c_22_k1
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
        # hot_tolerance: 0
        # cold_tolerance: 0
      target_sensor: sensor.floor_temperature_entrance
      min_temp: 18
      max_temp: 30
      precision: 0.1

    - platform: smart_thermostat
      name: floor_thermostat_bathroom_1_floor
      heater:
        entity_id:  switch.wb1_wb_mr6c_28_k1
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
        # hot_tolerance: 0
        # cold_tolerance: 0
      target_sensor: sensor.floor_temperature_bathroom_1_floor
      min_temp: 18
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: floor_thermostat_laundry
      heater:
        entity_id:  switch.wb1_wb_mr6c_28_k6
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
      target_sensor: sensor.floor_temperature_laundry
      min_temp: 18
      max_temp: 30
      precision: 0.1

    - platform: smart_thermostat
      name: floor_thermostat_stairs_outside
      heater:
        entity_id:  switch.wb1_wb_mr6cu_35_k1
        pid_params: 10, 0.004, 0
        pid_sample_period: "00:00:05"
        pwm_period: "00:05:00"
        # hot_tolerance: 0
        # cold_tolerance: 0
      target_sensor: sensor.floor_temperature_stairs_outside_1
      min_temp: 5
      max_temp: 20
      precision: 0.1
````

**Comment by hacker-cb** [comment]
My room thermostats:

```yaml
  climate:
    - platform: smart_thermostat
      name: thermostat_guestroom
      heater:
        - entity_id: switch.wb1_wb_mr6c_22_k2
          pid_params: 0.1, 0.001, 0
          pid_sample_period: "00:01:00"
          pwm_period: "00:05:00"
      cooler: input_boolean.thermostat_guestroom_demand_cool
      target_sensor: sensor.thermometer_guestroom_temperature
      min_temp: 15
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: thermostat_children
      heater:
        - entity_id: switch.wb1_wb_mr6c_22_k5
          pid_params: 0.1, 0.001, 0
          pid_sample_period: "00:01:00"
          pwm_period: "00:05:00"
      cooler: input_boolean.thermostat_children_demand_cool
      target_sensor: sensor.thermometer_children_temperature
      min_temp: 15
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: thermostat_cabinet
      heater:
        - entity_id: switch.wb1_wb_mr6c_22_k3
          pid_params: 0.1, 0.001, 0
          pid_sample_period: "00:01:00"
          pwm_period: "00:05:00"
      cooler: input_boolean.thermostat_cabinet_demand_cool
      target_sensor: sensor.thermometer_cabinet_temperature
      min_temp: 15
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: thermostat_bedroom
      heater:
        - entity_id: switch.wb1_wb_mr6c_22_k4
          pid_params: 0.1, 0.001, 0
          pid_sample_period: "00:01:00"
          pwm_period: "00:05:00"
      cooler: input_boolean.thermostat_bedroom_demand_cool
      target_sensor: sensor.thermometer_bedroom_temperature
      min_temp: 15
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: thermostat_livingroom
      heater:
        - entity_id: climate.floor_thermostat_livingroom_east
          pid_params: 0.001, 0.0001, 0
          pid_sample_period: "00:01:00"
        - entity_id: climate.floor_thermostat_livingroom_middle
          pid_params: 0.001, 0.0001, 0
          pid_sample_period: "00:01:00"
        - entity_id: climate.floor_thermostat_kitchen
          pid_params: 0.001, 0.0001, 0
          pid_sample_period: "00:01:00"

      cooler: input_boolean.thermostat_livingroom_demand_cool
      target_sensor: sensor.thermometer_livingroom_temperature
      min_temp: 15
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: thermostat_room_1
      heater:
        - entity_id: climate.floor_thermostat_room_1_floor
          pid_params: 0.001, 0.0001, 0
          pid_sample_period: "00:01:00"
      target_sensor: sensor.thermometer_room_1_temperature
      cooler: input_boolean.thermostat_room_1_demand_cool
      min_temp: 15
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: thermostat_bathroom_1
      heater:
        - entity_id: climate.floor_thermostat_bathroom_1_floor
          pid_params: 0.001, 0.0001, 0
          pid_sample_period: "00:01:00"
      cooler: input_boolean.thermostat_bathroom_1_demand_cool
      target_sensor: sensor.thermometer_bathroom_1_temperature
      min_temp: 15
      max_temp: 28
      precision: 0.1

    - platform: smart_thermostat
      name: thermostat_bathroom_2
    #   heater:
    #     entity_id: input_boolean.thermostat_bathroom_2_demand_heat
      cooler: input_boolean.thermostat_bathroom_2_demand_cool
      target_sensor: sensor.multisensor_bathroom_2_temperature
      min_temp: 15
      max_temp: 28
      precision: 0.1
```
